name: Reusable - Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'
      install-command:
        description: 'Command to install project dependencies'
        required: false
        type: string
        default: 'pip install -e ".[dev]"'
      upload-coverage:
        description: 'Whether to upload coverage to codecov'
        required: false
        type: boolean
        default: true

jobs:
  comprehensive-tests:
    runs-on: ubuntu-latest
    name: Comprehensive Tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        ${{ inputs.install-command }}
    
    - name: Run unit tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        if [ -d "tests/unit" ]; then
          pytest tests/unit/ --cov=. --cov-report=xml --cov-report=term-missing -v
        fi
    
    - name: Run integration tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        if [ -d "tests/integration" ]; then
          pytest tests/integration/ -v -s --tb=short || true
        fi
    
    - name: Upload coverage
      if: ${{ inputs.upload-coverage }}
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false