name: Reusable - Complete Python CI

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'
      ruff-config-path:
        description: 'Path to custom ruff config'
        required: false
        type: string
        default: ''
      install-command:
        description: 'Command to install project dependencies'
        required: false
        type: string
        default: 'pip install -e ".[dev]"'
      skip-commit-check:
        description: 'Skip commit message check'
        required: false
        type: boolean
        default: false
      skip-format-check:
        description: 'Skip format check'
        required: false
        type: boolean
        default: false
      skip-type-check:
        description: 'Skip type check'
        required: false
        type: boolean
        default: false
      skip-tests:
        description: 'Skip tests'
        required: false
        type: boolean
        default: false
      skip-precommit:
        description: 'Skip pre-commit checks'
        required: false
        type: boolean
        default: false  
    secrets:
      organization_access_token:
        required: true

jobs:
  pre-commit:
    if: ${{ !inputs.skip-precommit }}
    uses: ./.github/.github/workflows/reusable-precommit.yml@main
    with:
      python-version: ${{ inputs.python-version }}
    secrets:
      organization_access_token: ${{ secrets.organization_access_token }}
  
  commit-check:
    if: ${{ !inputs.skip-commit-check }}
    needs: pre-commit
    uses: ./.github/workflows/reusable-commit-check.yml@main
    with:
      python-version: ${{ inputs.python-version }}
    secrets:
      organization_access_token: ${{ secrets.organization_access_token }}
  
  format-check:
    if: ${{ !inputs.skip-format-check }}
    needs: pre-commit
    uses: ./.github/workflows/reusable-format-check.yml@main
    with:
      python-version: ${{ inputs.python-version }}
      ruff-config-path: ${{ inputs.ruff-config-path }}
      install-command: ${{ inputs.install-command }}
    secrets:
      organization_access_token: ${{ secrets.organization_access_token }}
  
  type-check:
    if: ${{ !inputs.skip-type-check }}
    needs: pre-commit
    uses: ./.github/workflows/reusable-type-check.yml@main
    with:
      python-version: ${{ inputs.python-version }}
      install-command: ${{ inputs.install-command }}
    secrets:
      organization_access_token: ${{ secrets.organization_access_token }}
  
  tests:
    if: ${{ !inputs.skip-tests }}
    needs: pre-commit
    uses: ./.github/workflows/reusable-tests.yml@main
    with:
      python-version: ${{ inputs.python-version }}
      install-command: ${{ inputs.install-command }}